## Frame Parameters
# ROBOT_FRAME: "base_link"

# Distance to the tracked person
DISTANCE: 1.5

# Scan angle resolution
SCAN_ANGLE_RESOLUTION: 0.087

# Robot Size Parameters
# FOOTPRINT: [[-0.2800, -0.1600], [-0.2800, 0.1600], [0.1200, 0.1600], [0.1200, -0.1600]]
FOOTPRINT:
  [[0.1600, 0.1200], [-0.1600, 0.1200], [-0.1600, -0.2800], [0.1600, -0.2800]]

FOOTPRINT_PADDING: 0.0 # [m], If localmap contains padding, you should set this param to 0.0