## Frame Parameters
# ROBOT_FRAME: "base_link"

# Distance to the tracked person
DISTANCE: 2.0

# Enable back movement
ENABLE_BACK: False

# Simulation Parameters
PREDICT_TIME: 3.0
SIM_TIME_SAMPLES: 10
MAX_LINEAR_VEL: 0.2
MAX_ANGULAR_VEL: 0.5

# PID Parameters for Rotation
KP: 0.25
KI: 0.5
KD: 0.1

# PID Parameters for Linear Velocity
KP_LINEAR_VEL: 0.3
KI_LINEAR_VEL: 0.0
KD_LINEAR_VEL: 0.1

# PID Parameters for Angular Velocity
KP_ANGULAR_VEL: 1.0
KI_ANGULAR_VEL: 0.5
KD_ANGULAR_VEL: 0.2

# Scan angle resolution
SCAN_ANGLE_RESOLUTION: 0.087

# Robot Size Parameters
# FOOTPRINT: [[-0.2800, -0.1600], [-0.2800, 0.1600], [0.1200, 0.1600], [0.1200, -0.1600]]
FOOTPRINT:
  # [[0.1600, 0.1200], [-0.1600, 0.1200], [-0.1600, -0.2800], [0.1600, -0.2800]]
  [[-0.2800, -0.1600], [-0.2800, 0.1600], [0.1200, 0.1600], [0.1200, -0.1600]]

FOOTPRINT_PADDING: 0.0 # [m], If localmap contains padding, you should set this param to 0.0
